name: Build Services

on:
  push:
    branches:
      - main

jobs:

  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      loan: ${{ steps.filter.outputs.loan }}
      payment: ${{ steps.filter.outputs.payment }}

    steps:
      - uses: actions/checkout@v3

      - name: Detect service changes
        uses: dorny/paths-filter@v2
        id: filter

        with:
          filters: |
            loan:
              - 'loan-service/**'
            payment:
              - 'payment-service/**'

      - name: Save result
        run: |
          echo "loan=${{ steps.filter.outputs.loan }}" >> $GITHUB_ENV
          echo "payment=${{ steps.filter.outputs.payment }}" >> $GITHUB_ENV