name: CI/CD Monorepo

on:
  push:
    branches:
      - main

jobs:

  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      loan: ${{ steps.filter.outputs.loan }}
      payment: ${{ steps.filter.outputs.payment }}

    steps:

      - uses: actions/checkout@v3

      - name: Detect service changes
        uses: dorny/paths-filter@v2
        id: filter

        with:
          filters: |
            loan:
              - 'loan-service/**'
            payment:
              - 'payment-service/**'

  build-loan:

    needs: detect-changes
    if: needs.detect-changes.outputs.loan == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Loan Service
        run: |
          echo "Building loan-service"


  build-payment:

    needs: detect-changes
    if: needs.detect-changes.outputs.payment == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Payment Service
        run: |
          echo "Building payment-service"


  package-loan:

    needs: build-loan
    if: needs.detect-changes.outputs.loan == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Package Loan
        run: |
          echo "Packaging loan-service"
          tar -czf loan-service.tar.gz loan-service


  package-payment:

    needs: build-payment
    if: needs.detect-changes.outputs.payment == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Package Payment
        run: |
          echo "Packaging payment-service"
          tar -czf payment-service.tar.gz payment-service


  deploy-loan:

    needs: package-loan
    if: needs.detect-changes.outputs.loan == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Loan Service
        run: |
          echo "Deploying loan-service"


  deploy-payment:

    needs: package-payment
    if: needs.detect-changes.outputs.payment == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Payment Service
        run: |
          echo "Deploying payment-service"