name: Monorepo Deploy

on:
  push:
    branches:
      - main

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      loan: ${{ steps.filter.outputs.loan }}
      payment: ${{ steps.filter.outputs.payment }}

    steps:
      - uses: actions/checkout@v3

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: filter

        with:
          filters: |
            loan:
              - 'loan-service/**'
            payment:
              - 'payment-service/**'

  deploy-loan:
    needs: detect-changes
    if: needs.detect-changes.outputs.loan == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Loan
        run: |
          echo "Deploying Loan Service"
          ls loan-service

  deploy-payment:
    needs: detect-changes
    if: needs.detect-changes.outputs.payment == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Payment
        run: |
          echo "Deploying Payment Service"
          ls payment-service