name: Payment CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'payment-service/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Building payment service"

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Packaging payment service"

  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying payment service"